### ISSUE TITLE
Release 3.0 checklist

### ISSUE THREAD

**Issue by jpuri** [jpuri/react-range-slider#5]
- [x] add new component for v-slider with single handle
- [x] unit test coverage for new component for v-slider with single handle
- [x] add new component for v-slider with two handle
- [x] unit test coverage for new component for v-slider with two handle
- [ ] improve default styles
